look for droute_send_template.json in $GITHUB_ACTION_PATH (#58)
* look for droute_send_template.json in $GITHUB_ACTION_PATH

* test TEMPLATE isn't empty

* skip find droute_send_template, give direct path

Co-authored-by: Daniele <36171005+dtrifiro@users.noreply.github.com>

* test droute_sent_template.json exists before using it.

* correct logic

* improve bash for consistency

Co-authored-by: Tarun Kumar <takumar@redhat.com>

---------

Co-authored-by: Daniele <36171005+dtrifiro@users.noreply.github.com>
Co-authored-by: Tarun Kumar <takumar@redhat.com>

diff --git a/actions/reportportal_submit_execution_results/action.yml b/actions/reportportal_submit_execution_results/action.yml
--- a/actions/reportportal_submit_execution_results/action.yml
+++ b/actions/reportportal_submit_execution_results/action.yml
@@ -70,7 +70,12 @@ runs:
         ls $TEST_RESULTS
 
         # generate report metadata file
-        TEMPLATE=`find ~ -type f -name 'droute_send_template.json'`
+        TEMPLATE="${GITHUB_ACTION_PATH}/droute_send_template.json"
+        if [[ ! -f "$TEMPLATE" ]]; then
+          echo "droute_send_template.json not found in $GITHUB_ACTION_PATH"
+          exit 1
+        fi
+
         echo "Generating datarouter.json based on template $TEMPLATE"
         jq --raw-output \
            --slurpfile metadata ${{ inputs.metadata_filepath }} \
